import tkinter as tk
from tkinter import *
window = tk.Tk()
window.title("Cost calculator")
window.geometry("550x460")

Label(window, text='CANNON').grid(row=0)
Label(window, text='Caliber').grid(row=1)
Label(window, text='Propellant length').grid(row=2)
Label(window, text='Barrel length').grid(row=3)
Label(window, text='ARMOUR').grid(row=5)
Label(window, text='Total weight').grid(row=6)
Label(window, text='Armour weight %').grid(row=7)
Label(window, text='ENGINE').grid(row=9)
Label(window, text='Cylinder count').grid(row=10)
Label(window, text='Displacement').grid(row=11)
Label(window, text='TRANSMISSION').grid(row=13)
Label(window, text='Gear count').grid(row=14)
Label(window, text='Type').grid(row=15)
TrT = IntVar()
Label(window, text='SUSPENSION').grid(row=0, column=4)
Label(window, text='Suspension count').grid(row=1, column=4)
Label(window, text='Axle count').grid(row=2, column=4)
Label(window, text='Suspender count').grid(row=3, column=4)
Label(window, text='Wheel diameter').grid(row=4, column=4)
Label(window, text='Suspension type').grid(row=5, column=4)
SusT = IntVar()
Label(window, text='TRACKS').grid(row=7, column=4)
Label(window, text='Width').grid(row=8, column=4)
Label(window, text='Thickness').grid(row=9, column=4)
Label(window, text='ADDITIONAL ARMOUR').grid(row=11, column=4)
Label(window, text='Segment Count').grid(row=12, column=4)
Label(window, text='Wheel count').grid(row=13, column=4)
Label(window, text='FUEL').grid(row=15, column=4)
Label(window, text='Fuel Capacity').grid(row=16, column=4)
Label(window, text='AMMO').grid(row=17)
Label(window, text='Ammo count').grid(row=18)
button = tk.Button(window, text='Calculate', width=12, height=2)
button.grid(row=18, column=4)
for i in range(0,20):
  Label(window,text='               ').grid(row=i,column=3)

def handle_click(event):
    cannon_cost = int((int(Ce1.get()) / 10) ** 2 * int(Ce2.get()) / 300 * int(Ce3.get()) / 1000 * 5)
    armour_cost = int(float(ARe1.get()) * float(ARe2.get()) * 2.5)
    engine_cost = int((int(Ee1.get()) ** 2) * float(Ee2.get()) * 5)
    transmission_cost = int(TMe1.get()) * 50
    if TrT.get() == 2:
        transmission_cost *= 1.5
        transmission_cost = int(transmission_cost)
    if SusT.get() == 1:
        suspension_cost = int((int(Se1.get()) * 5) + (int(Se1.get()) * int(Se2.get()) * float(Se4.get()) * 20 / 0.5) + (int(Se3.get()) * 10)) * 2
    else:
        suspension_cost = int((int(Se1.get()) * 50) + (int(Se2.get()) * 40 * float(Se4.get()) / 0.5) + (int(Se3.get()) * 10)) * 2
    tracks_cost = int((int(Te1.get()) / 300 * int(Te2.get()) / 50) ** 2) * 200
    additional_armour_cost = int((int(AAe1.get()) * ((int(Te2.get()) / 50) ** 2) * 15) + int(AAe2.get()) * 50)
    fuel_cost = int(float(Fe1.get()) * 2)
    ammo_cost = int(AMe1.get()) * ((int(Ce1.get())/10) ** 2) * int(Ce2.get()) / 300 / 10
    result = int(cannon_cost + armour_cost + engine_cost + transmission_cost + suspension_cost + additional_armour_cost + fuel_cost + tracks_cost + ammo_cost)
    Re1.delete(0, 'end')
    Re1.insert(END, str(result))

button.bind("<Button-1>", handle_click)

Ce1 = Entry(window)
Ce2 = Entry(window)
Ce3 = Entry(window)
ARe1 = Entry(window)
ARe2 = Entry(window)
Ee1 = Entry(window)
Ee2 = Entry(window)
TMe1 = Entry(window)
Se1 = Entry(window)
Se2 = Entry(window)
Se3 = Entry(window)
Se4 = Entry(window)
Te1 = Entry(window)
Te2 = Entry(window)
AAe1 = Entry(window)
AAe2 = Entry(window)
Fe1 = Entry(window)
AMe1 = Entry(window)
Re1 = Entry(window)

Ce1.insert(0, '0')
Ce2.insert(0, '0')
Ce3.insert(0, '0')
ARe1.insert(0, '0')
ARe2.insert(0, '0')
Ee1.insert(0, '0')
Ee2.insert(0, '0')
TMe1.insert(0, '0')
Se1.insert(0, '0')
Se2.insert(0, '0')
Se3.insert(0, '0')
Se4.insert(0, '0')
Te1.insert(0, '0')
Te2.insert(0, '0')
AAe1.insert(0, '0')
AAe2.insert(0, '0')
Fe1.insert(0, '0')
AMe1.insert(0, '0')
Re1.insert(0, '0')

Ce1.grid(row=1, column=1)
Ce2.grid(row=2, column=1)
Ce3.grid(row=3, column=1)
ARe1.grid(row=6, column=1)
ARe2.grid(row=7, column=1)
Ee1.grid(row=10, column=1)
Ee2.grid(row=11, column=1)
TMe1.grid(row=14, column=1)
Se1.grid(row=1, column=5)
Se2.grid(row=2, column=5)
Se3.grid(row=3, column=5)
Se4.grid(row=4, column=5)
Te1.grid(row=8, column=5)
Te2.grid(row=9, column=5)
AAe1.grid(row=12, column=5)
AAe2.grid(row=13, column=5)
Fe1.grid(row=16, column=5)
AMe1.grid(row=18, column=1)
Re1.grid(row=18, column=5)

Radiobutton(window, text='Clutch', variable=TrT, value=1).grid(row=15, column=1)
Radiobutton(window, text='Twin    ', variable=TrT, value=2).grid(row=16, column=1)
Radiobutton(window, text='Torsion bar', variable=SusT, value=1).grid(row=5, column=5)
Radiobutton(window, text='Bogie          ', variable=SusT, value=2).grid(row=6, column=5)

tk.mainloop()